config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    member do
      post :fetch
      get :diff
    end
  end
  root 'repositories#index'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :tags
  has_many :branches

  after_create :update_repository
  before_save :update_pulled_at

  # Fetches the repository
  def fetch
    update_repository
    update_pulled_at
    save!
  end

  def diff(from, to)
    Dir.chdir(path) do
      Diff.parse(`git diff --no-color -U10 #{from.name} #{to.name}`)
    end
  end

  protected

  # updates pulled_at row
  def update_pulled_at
    self.pulled_at = Time.now
  end

  # Fetches the repository
  def update_repository
    if File.exist?(path)
      Dir.chdir(path) do
        system('git', 'fetch')
      end
    else
      Dir.chdir(root) do
        system('git', 'clone', '--bare', '--local', url, id.to_s)
      end
    end

    update_tags
    update_branches

    true
  end

  # Update tags database
  def update_tags
    known_tags = tags.to_a
    Dir.chdir(path) do
      `git tag --no-column`.lines.each do |name|
        name = name.chomp

        tag = known_tags.delete_if { |t| t.name == name }.first
        tags.create(name: name) unless tag
      end
    end

    # Delete tags that do not exist anymore
    known_tags.each { |t| t.delete }
  end

  # Update branch database
  def update_branches
    known_branches = branches.to_a
    Dir.chdir(path) do
      `git branch --list --no-column --no-color`.lines.each do |name|
        name = branch_name(name)

        branch = known_branches.delete_if { |b| b.name == name }.first
        branches.create(name: name) unless branch
      end
    end

    # Delete tags that do not exist anymore
    known_branches.each { |b| b.delete }
  end

  # get branch name
  def branch_name(name)
    name.chomp.split(' ').last
  end

  # Internal path to repository
  def path
    File.join(root, id.to_s)
  end

  # Root of our repositories
  def root
    File.join(Rails.root, 'repositories')
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy, :fetch, :diff]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(create_repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(update_repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /repositories/1/fetch
  # POST /repositories/1/fetch.json
  def fetch
    @repository.fetch
    respond_to do |format|
      format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
      format.json { head :no_content }
    end
  end

  # GET /repositories/1/diff
  def diff
    @from = source(params[:from])
    @to = source(params[:to])

    redirect_to @repository, alert: 'Could not compare given versions.' unless @from && @to

    @diff = @repository.diff(@from, @to)
  end

  private
    # Gets the correct source object (or nil)
    def source(name)
      if name =~ /^tag(\d+)$/
        @repository.tags.find($1)
      elsif name =~ /^branch(\d+)$/
        @repository.branches.find($1)
      else
        nil
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_repository_params
      params.require(:repository).permit(:name, :url)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_repository_params
      params.require(:repository).permit(:name)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
  def port(line)
    Porter.port(line)
  end

  def diff_title(file)
    if file[0] == file[1]
      file[1]
    else
      (file[0] || '/dev/null') + ' -> ' + (file[1] || '/dev/null')
    end
  end

  def diff_port(line)
    Porter.port(line)
  end

  def diff_code(line)
    line = ' ' if line.blank?
    line = CGI.escapeHTML(line)
    raw line.gsub(' ', '&nbsp;')
  end

  def diff_php_file?(file)
    ( file[0] && file[0] =~ /\.php$/ ) ||
        (file[1] && file[1] =~ /\.php$/ )
  end
end

app/views/repositories/_form.html.haml
= semantic_form_for @repository do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name, label: 'Name'
    - if @repository.new_record?
      = f.input :url, label: 'URL to repository', hint: 'I recommend using http(s)'
    - else
      = f.input :url, label: 'URL to repository', hint: 'I recommend using http(s)', input_html: { disabled: true }

  = f.actions do
    = f.action :submit, label: 'Save'

app/views/repositories/diff.html.haml
.container-fluid
  %h1 #{@repository.name}: #{@from.name} .. #{@to.name}

  - @diff.each do |file, lines|
    .row
      %h2= diff_title(file)

      .col-md-6
        .diff-code
          - lines.each do |line|
            %div{ class: "diff-type-#{line[:type]}" }= diff_code(line[:line])

      - if diff_php_file?(file)
        .col-md-6
          .diff-code
            - lines.each do |line|
              %div{ class: "diff-type-#{line[:type]}" }= diff_code(diff_port(line[:line]))

  %p= link_to 'back', repository_path(@repository)

app/views/repositories/edit.html.haml
.container
  %h1 Editing Repository

  = render 'form'

app/views/repositories/index.html.haml
.container
  %h1 Available Repositories

  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Url
        %th Pulled at
    %tbody
      - @repositories.each do |repository|
        %tr
          %td= link_to repository.name, repository_path(repository)
          %td= repository.url
          %td= l repository.pulled_at

  %p= link_to 'Add Repository', new_repository_path

app/views/repositories/new.html.haml
.container
  %h1 Add Repository

  = render 'form'

app/views/repositories/show.html.haml
.container
  %h1= @repository.name

  %p
    = link_to 'Edit name', edit_repository_path(@repository)
    \|
    = link_to 'Delete', @repository, method: :delete, data: { confirm: 'Are you sure?' }

  %p
    %strong Url:
    = @repository.url

  %p
    %strong Pulled at:
    = l @repository.pulled_at

  = form_tag fetch_repository_path(@repository), method: :post do
    = submit_tag 'Update repository', class: 'btn btn-primary'

  %h2 Compare

  = form_tag diff_repository_path(@repository), method: :get do
    .row
      .col-md-6
        %h3 Tags

        %table.table.table-striped
          %thead
            %tr
              %th From
              %th To
          %tbody
            - @repository.tags.each do |tag|
              %tr
                %td
                  = radio_button_tag 'from', "tag#{tag.id}"
                  = label_tag "from_tag#{tag.id}", tag.name
                %td
                  = radio_button_tag 'to', "tag#{tag.id}"
                  = label_tag "to_tag#{tag.id}", tag.name

      .col-md-6
        %h3 Branches

        %table.table.table-striped
          %thead
            %tr
              %th From
              %th To
          %tbody
            - @repository.branches.each do |branch|
              %tr
                %td
                  = radio_button_tag 'from', "branch#{branch.id}"
                  = label_tag "from_branch#{branch.id}", branch.name
                %td
                  = radio_button_tag 'to', "branch#{branch.id}"
                  = label_tag "to_branch#{branch.id}", branch.name

    = submit_tag 'Compare!', class: 'btn btn-primary'